### ISSUE TITLE
Not working with 5.2 ?

### ISSUE THREAD

**Issue by kiyoshi-satoo** [wagtail/wagtail-localize#740]
I get this after update:
`cannot import name 'PagePreviewSidePanel' from 'wagtail.admin.ui.side_panels'`

I see in the release notes that you need to [update](https://docs.wagtail.org/en/latest/releases/5.2.html#basesidepanels-pagesidepanels-and-snippetsidepanels-classes-are-removed) where it is used.But apparently you forgot to update it here.Or am I doing something wrong ?

**Comment by zerolab** [comment]
@kiyoshi-satoo this was previously raised in #734, and fixed in #735. You can use `wagtail-localize==1.7rc1` in your requirements.txt file (or the corresponding syntax in your package manager of choice). I chose to do a release candidate to get a bit of real testing and address any issues before making a full release at the end of the week

Btw, a good rule of thumb is to search all issues/PRs rather than just the open ones. Or check the `CHANGELOG` file on the main branch
