### ISSUE TITLE
Error when trying to edit translated page

### ISSUE THREAD

**Issue by Warqus** [wagtail/wagtail-localize#231]
When trying to edit a translated page

```
Internal Server Error: /pages/7/edit/
Traceback (most recent call last):
  File "C:\Work\virtual_env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Work\virtual_env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Work\virtual_env\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\wagtail\admin\urls\__init__.py", line 127, in wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\wagtail\admin\auth.py", line 193, in decorated_view
    return view_func(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\wagtail\admin\views\pages\edit.py", line 114, in dispatch
    response = self.run_hook('before_edit_page', self.request, self.page)
  File "C:\Work\virtual_env\lib\site-packages\wagtail\admin\views\generic.py", line 60, in run_hook
    result = fn(*args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\wagtail_localize\wagtail_hooks.py", line 137, in before_edit_page
    return edit_translation.edit_translation(request, translation, page)
  File "C:\Work\virtual_env\lib\site-packages\wagtail_localize\views\edit_translation.py", line 395, in edit_translation
    for segment in string_segments
  File "C:\Work\virtual_env\lib\site-packages\wagtail_localize\views\edit_translation.py", line 395, in <listcomp>
    for segment in string_segments
  File "C:\Work\virtual_env\lib\site-packages\wagtail_localize\views\edit_translation.py", line 223, in get_segment_location_info
    block_value = stream_blocks_by_id[block_id]
KeyError: '81074384-c517-4469-9ade-2a1e12ef8ccf'
```

**Comment by asarican** [comment]
+1

**Comment by kaedroho** [comment]
This one is strange, it suggests that the "segments" wagtail has extracted from your content have different block ids to the content...

It's hard for me to debug this one without being able to reproduce it locally. Please could you provide some example code and some instructions for how to reproduce it?

**Comment by Warqus** [comment]
I've tried to reproduce it and ran into another error (which is already fixed and currently in review I think):

```
'CharBlock' object has no attribute 'child_blocks'
```

If all new fixes are pushed, I can try to reproduce the issue mentioned in this thread.

**Comment by patillacode** [comment]
@Warqus I've been having the same issue and it has been fixed.
Working in release [0.9.3](https://github.com/wagtail/wagtail-localize/releases/tag/v0.9.3)

**Comment by Warqus** [comment]
@patillacode Thanks for notifying me! The error hasn't occurred while using 0.9.3 👍

**Comment by kaedroho** [comment]
Interesting, I'm not sure why it works, but obviously great that it does!

I'm going to close this for now, since I haven't got anything to use to investigate. Please reopen if it occurs again.

**Comment by Alex0jk** [comment]
Hey, I think I have stumbled into this issue or a very similar one. This is the error I get:

```
Traceback (most recent call last):
  File "/work/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/work/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/work/venv/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/work/venv/lib/python3.8/site-packages/wagtail/admin/urls/__init__.py", line 127, in wrapper
    return view_func(request, *args, **kwargs)
  File "/work/venv/lib/python3.8/site-packages/wagtail/admin/auth.py", line 172, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/work/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/work/venv/lib/python3.8/site-packages/wagtail/admin/views/pages/edit.py", line 114, in dispatch
    response = self.run_hook('before_edit_page', self.request, self.page)
  File "/work/venv/lib/python3.8/site-packages/wagtail/admin/views/generic/hooks.py", line 16, in run_hook
    result = fn(*args, **kwargs)
  File "/work/venv/lib/python3.8/site-packages/wagtail_localize/wagtail_hooks.py", line 148, in before_edit_page
    return edit_translation.edit_translation(request, translation, page)
  File "/work/venv/lib/python3.8/site-packages/wagtail_localize/views/edit_translation.py", line 508, in edit_translation
    location_info = get_segment_location_info(source_instance, tab_helper, segment.context.path)
  File "/work/venv/lib/python3.8/site-packages/wagtail_localize/views/edit_translation.py", line 331, in get_segment_location_info
    block_value = stream_blocks_by_id[block_id]
KeyError: 'ef877559-059a-4df1-b448-732e0983507d'
ERROR django.server "GET /pages/24692/edit/ HTTP/1.1" 500 159970
```

This time, I have a way to reproduce it. This is happening when working with a StreamField. Imagine you have a StreamField that allows adding blocks A and B into the page. If we create a page with block A and B, then translate it to any language, let say Spanish, everything works fine. We can update the translations with no problem. Then, if we go to the source page, remove block A and publish; when we try to edit the translation it throws the error. The error is solved if we sync the translations with the source page.

What I think is happening is that when the translated page is trying to get the blocks from the source by their ids, it cant not find the block so it breaks.

**Comment by ahmedbilal** [comment]
@kaedroho @Alex0jk I recently come across this error but it is happening even before there is a translation at all. 
```
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/cms/localize/submit/page/10/?next=%2Fcms%2Fpages%2F6%2F

Django Version: 3.2.3
Python Version: 3.9.5
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'rest_framework',
 'widget_tweaks',
 'catalog',
 'webpack_loader',
 'import_export',
 'debug_toolbar',
 'django_json_widget',
 'wagtail.search',
 'wagtail_localize',
 'wagtail_localize.locales',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.admin',
 'wagtail.core',
 'modelcluster',
 'taggit',
 'cms']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware']



Traceback (most recent call last):
  File "/home/meow/Desktop/ungleich/alpinesmuseum/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/meow/Desktop/ungleich/alpinesmuseum/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/meow/Desktop/ungleich/alpinesmuseum/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/meow/Desktop/ungleich/alpinesmuseum/venv/lib/python3.9/site-packages/wagtail/admin/urls/__init__.py", line 108, in wrapper
    return view_func(request, *args, **kwargs)
  File "/home/meow/Desktop/ungleich/alpinesmuseum/venv/lib/python3.9/site-packages/wagtail/admin/auth.py", line 193, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/home/meow/Desktop/ungleich/alpinesmuseum/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/meow/Desktop/ungleich/alpinesmuseum/venv/lib/python3.9/site-packages/wagtail_localize/views/submit_translations.py", line 193, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/meow/Desktop/ungleich/alpinesmuseum/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/meow/Desktop/ungleich/alpinesmuseum/venv/lib/python3.9/site-packages/wagtail_localize/views/submit_translations.py", line 157, in post
    translator.create_translations(self.object)
  File "/home/meow/Desktop/ungleich/alpinesmuseum/venv/lib/python3.9/site-packages/wagtail_localize/views/submit_translations.py", line 109, in create_translations
    translation.save_target(user=self.user)
  File "/home/meow/Desktop/ungleich/alpinesmuseum/venv/lib/python3.9/site-packages/wagtail_localize/models.py", line 1131, in save_target
    self.source.create_or_update_translation(self.target_locale, user=user, publish=publish, fallback=True, copy_parent_pages=True)
  File "/home/meow/Desktop/ungleich/alpinesmuseum/venv/lib/python3.9/site-packages/wagtail_localize/models.py", line 690, in create_or_update_translation
    ingest_segments(original, translation, self.locale, locale, segments)
  File "/home/meow/Desktop/ungleich/alpinesmuseum/venv/lib/python3.9/site-packages/wagtail_localize/segments/ingest.py", line 239, in ingest_segments
    StreamFieldSegmentsWriter(
  File "/home/meow/Desktop/ungleich/alpinesmuseum/venv/lib/python3.9/site-packages/wagtail_localize/segments/ingest.py", line 206, in handle_stream_block
    block.value = self.handle_block(block.block, block.value, segments)
  File "/home/meow/Desktop/ungleich/alpinesmuseum/venv/lib/python3.9/site-packages/wagtail_localize/segments/ingest.py", line 151, in handle_block
    return self.handle_struct_block(block_value, segments)
  File "/home/meow/Desktop/ungleich/alpinesmuseum/venv/lib/python3.9/site-packages/wagtail_localize/segments/ingest.py", line 180, in handle_struct_block
    block_type = struct_block.block.child_blocks[field_name]

Exception Type: KeyError at /cms/localize/submit/page/10/
Exception Value: 'modal_link_text'
```
