### ISSUE TITLE
wagtail_localize does not seem to work with Wagtail 5.2

### ISSUE THREAD

**Issue by wimfeijen** [wagtail/wagtail-localize#734]
After installation of Wagtail 5.2 and running python manage.py shell, I get the following error. I am using wagtail-localize==1.6. 

  File "[...]/lib/python3.9/site-packages/wagtail_localize/wagtail_hooks.py", line 23, in <module>
    from .views import (
  File "[...]/lib/python3.9/site-packages/wagtail_localize/views/edit_translation.py", line 63, in <module>
    from wagtail_localize.side_panels import LocalizedPageSidePanels
  File "[...]/lib/python3.9/site-packages/wagtail_localize/side_panels.py", line 2, in <module>
    from wagtail.admin.ui.side_panels import PagePreviewSidePanel, PageSidePanels
ImportError: cannot import name 'PagePreviewSidePanel' from 'wagtail.admin.ui.side_panels' ([...]/lib/python3.9/site-packages/wagtail/admin/ui/side_panels.py)

(In the above code, I omitted the location of our virtualenv directory and replaced that with [...])

**Comment by zerolab** [comment]
#733 is a start for the compatibility issue

**Comment by catilgan-nextension** [comment]
See my comment for other issues with wagtail_localize as well: https://github.com/aekong/wagtail-localize/pull/1#issuecomment-1792146516

**Comment by zerolab** [comment]
I've now opened #735, there is a link to a build with that version and I'd appreciate testing with real projects
