### ISSUE TITLE
Translation page for snippet with Page link in orderable throws error (v1.2 wagtail v3)

### ISSUE THREAD

**Issue by enzedonline** [wagtail/wagtail-localize#573]
Hi,

I've come across a bug with the new version (1.2). The code worked fine in wagtail 2.16.

I have a class with some fields and optional orderable types (3 classes), each of these types have ForeignKey attributes to link to another object. When I add an item to any of the 3 orderable types, the translation page throws the error:

```
Exception Type:	AttributeError
Exception Value:	'NoneType' object has no attribute 'get_form_options'
Exception Location:	...\lib\site-packages\wagtail_localize\views\edit_translation.py, line 327, in widget_from_field
```

In edit_translation.widget_from_field() line 320:
`edit_handler = tab_helper.get_field_edit_handler(field.name)`

No edit_handler is returned for field with property Django foreign key:

```
Variable	Value
edit_handler	None
field           <django.db.models.fields.related.ForeignKey: link_page>
tab_helper	<wagtail_localize.views.edit_translation.TabHelper object at 0x0000012D49601970>
```

The next block throws the error since `edit_handler` is an empty object:

```python
                    if WAGTAIL_VERSION >= (3, 0):
                        widget_overrides = edit_handler.get_form_options().get(
                            "widgets", {}
                        )
```

`link_page` is a ForeignKey field that links to another page:

```python
    link_page = models.ForeignKey(
        Page,
        blank=True,
        null=True,
        related_name="+",
        on_delete=models.CASCADE,
        help_text=_(
            "Use this to link to an internal page."
        ),
    )
```
If I delete all the orderables, translation page loads fine. If I add an orderable but don't include a ForeignKey attribute (e.g. don't link to another page), the translation page loads fine. Seems ForeignKey fields are the source of the issue.

EDIT: a bit of further investigation, one of the orderables has an optional ForeignKey field to load an image, this loads fine in translation when set, it's just the link to Page that seems to throw this.

Python 3.9.4
Wagtail 3.0
Django 4.04
Wagtail Localize 1.2

**Comment by zerolab** [comment]
Hey @enzedonline,
could you post a minimal example? I would've thought our testsuite would've caught this, given that #555 fixed the failures with Wagtail 3.0.
Perhaps we're missing an edge case

**Comment by enzedonline** [comment]
Hi @zerolab 

Yeah, I've manage to re-create it - it happens when the page link is in an orderable. In the following test object, the orderables are just replications of the parent. 

I started off with a base instance, with each field completed but no orderables added. The translation page loads fine.

I then added an orderable with each field completed, the error occurs.

Went back and removed the page link, leaving all other orderable fields intact, the translation page loads again.

Test app:

```
from django.db import models
from django.utils.translation import gettext_lazy as _
from modelcluster.fields import ParentalKey
from modelcluster.models import ClusterableModel
from wagtail.admin.panels import FieldPanel, InlinePanel
from wagtail.models import Orderable, TranslatableMixin, Page
from wagtail.snippets.models import register_snippet

@register_snippet
class TestObject(TranslatableMixin, ClusterableModel):
    text_field = models.CharField(
        max_length=30,
        null=False,
        blank=False,
        help_text=_("Some text")
    )
    url_field = models.URLField(
        max_length=100,
        null=True,
        blank=True,
        help_text=_("A URL")
    )
    image_field = models.ForeignKey(
        "wagtailimages.Image",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="+",
        help_text=_("An image")
    )  
    page_field = models.ForeignKey(
        Page,
        blank=True,
        null=True,
        related_name="+",
        on_delete=models.CASCADE,
        help_text=_(
            "Page link"
        ),
    )    
    panels = [
        FieldPanel('text_field'),
        FieldPanel('url_field'),
        FieldPanel('image_field'),
        FieldPanel('page_field'),
        InlinePanel('test_object', label="Orderable Items")
    ]
        
class OrderableItem(TranslatableMixin, Orderable):
    parent = ParentalKey(
        "TestObject",
        related_name="test_object",
        help_text=_("Parent to which this item belongs"),
    )    
    orderable_text_field = models.CharField(
        max_length=30,
        null=False,
        blank=False,
        help_text=_("Some text")
    )
    orderable_url_field = models.URLField(
        max_length=100,
        null=True,
        blank=True,
        help_text=_("A URL")
    )
    orderable_image_field = models.ForeignKey(
        "wagtailimages.Image",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="+",
        help_text=_("An image")
    )  
    orderable_page_field = models.ForeignKey(
        Page,
        blank=True,
        null=True,
        related_name="+",
        on_delete=models.CASCADE,
        help_text=_(
            "Page link"
        ),
    )    
    
    panels = [
        FieldPanel('orderable_text_field'),
        FieldPanel('orderable_url_field'),
        FieldPanel('orderable_image_field'),
        FieldPanel('orderable_page_field'),
    ]
    
```

Error as before:

```
Exception Value:	'NoneType' object has no attribute 'get_form_options'
Exception Location:	c:\Django\helenerodenposzler.com\.venv\lib\site-packages\wagtail_localize\views\edit_translation.py, line 327, in widget_from_field

Variable           Value
edit_handler	None
field	               <django.db.models.fields.related.ForeignKey: orderable_page_field>
tab_helper      <wagtail_localize.views.edit_translation.TabHelper object at 0x0000029C4A67D910>
```

I can see the `page_field `(from the parent object) pass through fine, but when it gets to the `orderable_page_field`, the problem occurs in the if statement in `edit_translation.TabHelper.get_field_edit_handler()` (Line 293 on this version)

```
    def get_field_edit_handler(self, field_name):
        if field_name in self.field_edit_handler_mapping:
            return self.field_edit_handler_mapping[field_name]
```
The field name is `orderable_page_field`, but `self.field_edit_handler_mapping` refers to the fields in the parent, not the orderable (in this case, `text_field, url_field, image_field, page_field` rather than `orderable_text_field, orderable_url_field, orderable_image_field, orderable_page_field`)

![image](https://user-images.githubusercontent.com/72310199/169777252-e84b9c49-5b46-48c9-8bf5-b6fd3b3ec1e3.png)

**Comment by enzedonline** [comment]
As a workaround, I thought to just make the page_link in the orderable non-translatable with

```
    override_translatable_fields = [
        TranslatableField('orderable_text_field'),
        TranslatableField('orderable_url_field'),
        TranslatableField('orderable_image_field'),
    ]  
```

However, the code still looks to load the field even though it's non-translatable.

**Comment by zerolab** [comment]
@enzedonline I will try to look at this tonight (GMT)

**Comment by enzedonline** [comment]
@zerolab no rush on my part, the production server is still on 2.x for the moment. Just a couple of ideas that popped up when I started this morning. I also tried a page link in a streamfield block on a page, that loads fine in the translated edit page.

**Comment by enzedonline** [comment]
This does work for me:

```
    override_translatable_fields = [
        SynchronizedField("orderable_page_field", overridable=False),
    ]
```   

Going back to my original use case, it makes sense to do this in any case since the translated page comes from the code anyway.

**Comment by enzedonline** [comment]
@zerolab ok, great!
I had a thought that I hadn't tried orderable documents, added a field for that
 ```
  orderable_document_field = models.ForeignKey(
        'wagtaildocs.Document',
        null=True,
        blank=True,
        related_name='+',
        on_delete=models.CASCADE,
    )    
```
As per the image field, it's not affected. Maybe there are some other types I'm missing to try.

**Comment by zerolab** [comment]
version 1.2.1 is now out

**Comment by enzedonline** [comment]
Hi @zerolab,

I've tested 1.2.1 against the model shown above. I can load without error and change the page field in the translation. Thanks for your speedy work on this!
